In [161]:
import pandas as pd
import math
import numpy as np

In [3]:
dataset=pd.read_csv("/Users/bhoomi/Documents/GitHub/Healthcare_Dashboard_Tableau/healthcare_dataset.csv") #extracting dataset
print(dataset) # printing dataset

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [8]:
dataset['Name']=dataset['Name'].str.title() #Messay name -> Proper name 
print(dataset['Name'])

0            Bobby Jackson
1             Leslie Terry
2              Danny Smith
3             Andrew Watts
4            Adrienne Bell
               ...
55495    Elizabeth Jackson
55496           Kyle Perez
55497         Heather Wang
55498       Jennifer Jones
55499         James Garcia
Name: Name, Length: 55500, dtype: object

In [9]:
dataset.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [18]:
print(dataset[dataset.duplicated()]) 
dataset.drop_duplicates(inplace=True) #Deleting duplicates
dataset.describe()

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

                Age  Billing Amount   Room Number
count  54966.000000    54966.000000  54966.000000
mean      51.535185    25544.306284    301.124404
std       19.605661    14208.409711    115.223143
min       13.000000    -2008.492140    101.000000
25%       35.000000    13243.718641    202.000000
50%       52.000000    25542.749145    302.000000
75%       68.000000    37819.858159    401.000000
max       89.000000    52764.276736    500.000000

In [19]:
dataset.isnull().sum() # Looking for NULL values in each column

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [37]:
dataset['Age']=dataset['Age'].astype(int)
dataset['Room Number']=dataset['Room Number'].astype(int)
dataset['Billing Amount']=round(dataset['Billing Amount'].astype(float),2)

dataset['Date of Admission']=dataset['Date of Admission'].astype('date32[pyarrow]')
dataset['Discharge Date']=dataset['Discharge Date'].astype('date32[pyarrow]')

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  object
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  object
 3   Blood Type          54966 non-null  object
 4   Medical Condition   54966 non-null  object
 5   Date of Admission   54966 non-null  date32[day][pyarrow]
 6   Doctor              54966 non-null  object
 7   Hospital            54966 non-null  object
 8   Insurance Provider  54966 non-null  object
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  object
 12  Discharge Date      54966 non-null  date32[day][pyarrow]
 13  Medication          54966 non-null  object
 14  Test Results        54966 non-null  object
dtypes: date32[day][pyarrow](2), float64(1), int64(2), object(10)
memory usage: 6.3+ MB

In [40]:
dataset[dataset['Name']=="Terry Wilson"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
29484,Terry Wilson,39,Male,O-,Diabetes,2024-02-19,Diana Smith,"Medina and Elliott Stewart,",Aetna,-1316.62,491,Emergency,2024-03-20,Paracetamol,Inconclusive
50099,Terry Wilson,43,Male,O-,Diabetes,2024-02-19,Diana Smith,"Medina and Elliott Stewart,",Aetna,-1316.62,491,Emergency,2024-03-20,Paracetamol,Inconclusive

In [ ]:
match_key=['Name','Medical Condition','Date of Admission','Doctor','Hospital','Insurance Provider','Billing Amount','Room Number','Admission Type','Discharge Date']
dataset.drop_duplicates(subset=(match_key),inplace=True)
print(dataset)

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                50000 non-null  object
 1   Age                 50000 non-null  int64
 2   Gender              50000 non-null  object
 3   Blood Type          50000 non-null  object
 4   Medical Condition   50000 non-null  object
 5   Date of Admission   50000 non-null  date32[day][pyarrow]
 6   Doctor              50000 non-null  object
 7   Hospital            50000 non-null  object
 8   Insurance Provider  50000 non-null  object
 9   Billing Amount      50000 non-null  float64
 10  Room Number         50000 non-null  int64
 11  Admission Type      50000 non-null  object
 12  Discharge Date      50000 non-null  date32[day][pyarrow]
 13  Medication          50000 non-null  object
 14  Test Results        50000 non-null  object
dtypes: date32[day][pyarrow](2), float64(1), int64(2), object(10)
memory usage: 5.7+ MB

In [47]:
dataset.to_csv('/Users/bhoomi/Documents/GitHub/Healthcare_Dashboard_Tableau/clean_healthcareDataset.csv')

EDA - Overview Dashboard

In [91]:
print(f"Total Patients: ",dataset['Name'].nunique())
print(f"Total Hospitals: ",dataset['Hospital'].nunique())
print(f"Total Bills paid: ",round(dataset['Billing Amount'].sum(),2))
print(f"Average Age of Patients: ",round(dataset['Age'].sum()/dataset['Age'].count()))
print(f"Total Insurance Companies: ",dataset['Insurance Provider'].nunique())

print(f"\nNumber of patients group by ",dataset.groupby('Blood Type')['Name'].count())

print(f"\nMinimum age & Max Age:",min(dataset['Age']),max(dataset['Age']))
age_bins=[0,17,24,44,64,100]
age_label=['Kids(age<18)','Young Adults(age>=18 and <25)','Adults(age>=25 & <45)','Middle aged(age>=45 and <65)','Retired(age>65)']
dataset['Age Distribution']=pd.cut(dataset['Age'],bins=age_bins,labels=age_label)
print("Number of patients based on their age group: ",dataset.groupby('Age Distribution',observed=True)['Age'].count())

print(f"\nNumber of Males ", (dataset['Gender']=='Male').sum())
print(f"Number of Females ",(dataset['Gender']=='Female').sum())

print(f"\nNumber of perople by ",dataset.groupby('Medical Condition',observed=True)['Name'].nunique())

room_bins=[100,199,299,399,499]
room_label=['100-200','200-300','300-400','400-500']
dataset['Room Utilization']=pd.cut(dataset['Room Number'],bins=room_bins,labels=room_label)
room_utilization_pivot=dataset.pivot_table(
    index='Room Utilization',
    columns='Admission Type',
    values='Room Number',
    aggfunc='count',
    observed=True
)
result = dataset.groupby(['Room Utilization', 'Admission Type'],observed=True)['Room Number'].count()
print(f"\n",result)

print(f"\nSum of billing amount per hospital: ")
result_billing_amt=dataset.groupby('Hospital',observed=True)['Billing Amount'].sum()
print(result_billing_amt.sort_values(ascending=False).head(10))

Total Patients:  40235
Total Hospitals:  39876
Total Bills paid:  1277784576.67
Average Age of Patients:  52
Total Insurance Companies:  5

Number of patients group by  Blood Type
A+     6246
A-     6261
AB+    6291
AB-    6259
B+     6278
B-     6230
O+     6235
O-     6200
Name: Name, dtype: int64

Minimum age & Max Age: 18 85
Number of patients based on their age group:  Age Distribution
Young Adults(age>=18 and <25)     5153
Adults(age>=25 & <45)            14593
Middle aged(age>=45 and <65)     14827
Retired(age>65)                  15427
Name: Age, dtype: int64

Number of Males  24989
Number of Females  25011

Number of perople by  Medical Condition
Arthritis       8019
Asthma          7837
Cancer          7853
Diabetes        7950
Hypertension    7870
Obesity         7844
Name: Name, dtype: int64

 Room Utilization  Admission Type
100-200           Elective          4059
                  Emergency         3975
                  Urgent            4164
200-300           Elective          4299
                  Emergency         4088
                  Urgent            4093
300-400           Elective          4203
                  Emergency         4196
                  Urgent            4334
400-500           Elective          4238
                  Emergency         4083
                  Urgent            4150
Name: Room Number, dtype: int64

Sum of billing amount per hospital:
Hospital
Johnson PLC    1040431.60
LLC Smith       948561.10
Ltd Smith       915166.77
Smith PLC       901359.29
Smith Ltd       897694.86
Group Smith     847450.76
Johnson Inc     806433.33
Inc Brown       801547.73
LLC Johnson     766627.99
Smith Group     740164.31
Name: Billing Amount, dtype: float64

EDA - Clinical Dashboard

In [128]:
print(f"Most common ",dataset.groupby('Medical Condition',observed=True)['Name'].count().sort_values(ascending=False).head(1))
print(f"\nAvg age of patient: ",round(dataset['Age'].sum()/dataset['Age'].count()))
print(f"\n% of Normal test result: ",round(dataset[dataset['Test Results']=='Normal']['Test Results'].count()*100)/dataset['Test Results'].count())
print(f"\n% of Abnormal test result: ",round(dataset[dataset['Test Results']=='Abnormal']['Test Results'].count()*100)/dataset['Test Results'].count())
print(f"\n% of Inconclusive test result: ",round(dataset[dataset['Test Results']=='Inconclusive']['Test Results'].count()*100)/dataset['Test Results'].count())
print(f"\nCondition by frequency: ",dataset.groupby('Medical Condition')['Name'].count())
print(f"\nMedical condition by\n",dataset.groupby(['Medical Condition','Admission Type'],observed=True)['Name'].count().unstack())
print(f"\nMedical condition Vs Medicine used\n ",dataset.groupby(['Medical Condition','Medication'])['Name'].count().unstack())
print(f"\nMedical condition vs billing amount:\n ",round(dataset.groupby('Medical Condition')['Billing Amount'].mean(),2))
print(f"\nTest Result breakdown:\n ",dataset.groupby('Test Results')['Name'].count())

Most common  Medical Condition
Arthritis    8439
Name: Name, dtype: int64

Avg age of patient:  52

% of Normal test result:  33.368

% of Abnormal test result:  33.544

% of Inconclusive test result:  33.088

Condition by frequency:  Medical Condition
Arthritis       8439
Asthma          8272
Cancer          8294
Diabetes        8384
Hypertension    8319
Obesity         8292
Name: Name, dtype: int64

Medical condition by
 Admission Type     Elective  Emergency  Urgent
Medical Condition
Arthritis              2823       2787    2829
Asthma                 2809       2690    2773
Cancer                 2819       2708    2767
Diabetes               2769       2712    2903
Hypertension           2884       2681    2754
Obesity                2723       2811    2758

Medical condition Vs Medicine used
  Medication         Aspirin  Ibuprofen  Lipitor  Paracetamol  Penicillin
Medical Condition
Arthritis             1733       1660     1663         1698        1685
Asthma                1619       1620     1649         1705        1679
Cancer                1607       1683     1725         1669        1610
Diabetes              1681       1679     1702         1627        1695
Hypertension          1683       1696     1658         1669        1613
Obesity               1669       1665     1635         1610        1713

Medical condition vs billing amount:
  Medical Condition
Arthritis       25486.20
Asthma          25681.21
Cancer          25234.70
Diabetes        25654.53
Hypertension    25494.22
Obesity         25784.00
Name: Billing Amount, dtype: float64

Test Result breakdown:  Test Results
Abnormal        16772
Inconclusive    16544
Normal          16684
Name: Name, dtype: int64

EDA - Financial Dashboard

In [146]:
print(f"Total bill paid: ",round(dataset['Billing Amount'].sum(),2))
print(f"\nAvg bill: ",round(dataset['Billing Amount'].mean()))
print(f"\nHighest billing",dataset.groupby('Hospital',observed=True)['Name'].count().sort_values(ascending=False).head(1))
print(f"\nTop ",dataset.groupby('Insurance Provider',observed=True)['Name'].count().sort_values(ascending=False).head(1))
print(f"\nBills paid to ",dataset.groupby('Hospital',observed=True)['Billing Amount'].sum().sort_values(ascending=False).head(1))
print(f"\nMedical condition vs Insurance provider\n",dataset.groupby(['Medical Condition','Insurance Provider'])['Name'].count().unstack())
print(f"\nHospital wise avg Billing amount: ",round(dataset.groupby('Admission Type')['Billing Amount'].mean(),2))
print(f"\nBilling by Gender\n",round(dataset.groupby('Gender',observed=True)['Billing Amount'].sum(),2))
print(f"Billing by Insurance provider: ",dataset.groupby('Insurance Provider')['Billing Amount'].sum())

Total bill paid:  1277784576.67

Avg bill:  25556

Highest billing Hospital
LLC Smith    40
Name: Name, dtype: int64

Top  Insurance Provider
Cigna    10091
Name: Name, dtype: int64

Bills paid to  Hospital
Johnson PLC    1040431.6
Name: Billing Amount, dtype: float64

Medical condition vs Insurance provider
 Insurance Provider  Aetna  Blue Cross  Cigna  Medicare  UnitedHealthcare
Medical Condition
Arthritis            1662        1691   1706      1685              1695
Asthma               1589        1659   1695      1648              1681
Cancer               1641        1620   1688      1678              1667
Diabetes             1668        1683   1679      1730              1624
Hypertension         1676        1638   1656      1650              1699
Obesity              1612        1710   1667      1667              1636

Hospital wise avg Billing amount:  Admission Type
Elective     25618.78
Emergency    25528.47
Urgent       25519.03
Name: Billing Amount, dtype: float64

Billing by Gender
 Gender
Female    6.373210e+08
Male      6.404636e+08
Name: Billing Amount, dtype: float64
Billing by Insurance provider:  Insurance Provider
Aetna               2.516910e+08
Blue Cross          2.565363e+08
Cigna               2.576307e+08
Medicare            2.577443e+08
UnitedHealthcare    2.541823e+08
Name: Billing Amount, dtype: float64

EDA - Trends

In [223]:
dataset['Avg Stay']=(dataset['Discharge Date']-dataset['Date of Admission']).dt.days
print(f"Avg stay: ",round(dataset['Avg Stay'].mean()))
dataset['Month of Date']=dataset['Date of Admission'].dt.month_name()
print(f"\nPeak Month: ",dataset.groupby('Month of Date',observed=True)['Name'].count().sort_values(ascending=False).head(1))
print(f"\nTotal admissions ",dataset['Name'].nunique())
print(f"\nBusiest ",dataset.groupby('Hospital')['Name'].nunique().sort_values(ascending=False).head(1))

dataset['Month-Year']=dataset['Date of Admission'].dt.strftime('%B-%Y')
print(f"\nAdmission by ",dataset.groupby('Month-Year')['Name'].count())
print(f"\nAvg stay by ",round(dataset.groupby('Medical Condition')['Avg Stay'].mean()))
print(f"\nSeasonal admission pattern\n ",dataset.groupby(['Month of Date','Admission Type'],observed=True)['Name'].count().unstack())
print(f"\nNumber of patients each year ",dataset.groupby(dataset['Date of Admission'].dt.year)['Name'].count())
def format_millions(x):
    return f"{x/1_000_000:.2f}M"
print(f"\nBilling over months of years\n ",dataset.groupby('Month-Year')['Billing Amount'].sum().apply(format_millions))

Avg stay:  16

Peak Month:  Month of Date
August    4353
Name: Name, dtype: int64

Total admissions  40235

Busiest  Hospital
LLC Smith    40
Name: Name, dtype: int64

Admission by  Month-Year
April-2020        835
April-2021        796
April-2022        783
April-2023        807
April-2024        843
                 ...
September-2019    846
September-2020    814
September-2021    799
September-2022    832
September-2023    831
Name: Name, Length: 61, dtype: int64

Avg stay by  Medical Condition
Arthritis       16.0
Asthma          16.0
Cancer          15.0
Diabetes        15.0
Hypertension    15.0
Obesity         15.0
Name: Avg Stay, dtype: double[pyarrow]

Seasonal admission pattern
  Admission Type  Elective  Emergency  Urgent
Month of Date
April               1371       1343    1350
August              1465       1398    1490
December            1432       1385    1402
February            1286       1314    1224
January             1428       1397    1419
July                1453       1417    1430
June                1430       1328    1471
March               1374       1385    1439
May                 1428       1375    1342
November            1383       1330    1395
October             1410       1353    1431
September           1367       1364    1391

Number of patients each year  Date of Admission
2019     6635
2020    10156
2021     9883
2022     9936
2023     9929
2024     3461
Name: Name, dtype: int64

Billing over months of years
  Month-Year
April-2020        21.06M
April-2021        20.62M
April-2022        20.08M
April-2023        20.55M
April-2024        20.98M
                   ...
September-2019    21.33M
September-2020    20.29M
September-2021    20.02M
September-2022    21.39M
September-2023    21.23M
Name: Billing Amount, Length: 61, dtype: object

EDA- DR & Hospital Performace

In [231]:
print(f"Total Doctors: ",dataset['Doctor'].nunique())
print(f"\nTop doctor by patients ",dataset.groupby('Doctor')['Name'].count().sort_values(ascending=False).head(1))
dataset['Stay']=(dataset['Discharge Date']-dataset['Date of Admission']).dt.days
print(f"\nAvg stay: ",round(dataset['Stay'].mean()))
print(f"\nAvg Bill: ",round(dataset['Billing Amount'].mean(),2))

print(f"\nTop 10 doctors by patient count: ",dataset.groupby('Doctor')['Name'].count().sort_values(ascending=False).head(10))
partial_testResultbyDoctorResult=dataset.groupby(['Doctor','Test Results'])['Name'].nunique().unstack()
partial_testResultbyDoctorResult['Total']=partial_testResultbyDoctorResult.sum(axis=1)
partial_testResultbyDoctorResult=partial_testResultbyDoctorResult.sort_values('Total',ascending=False).head(10)
print(f"\nTest Results by Doctors:\n ",partial_testResultbyDoctorResult)
print(f"\nNumber of patients by hospital: ",dataset.groupby('Hospital')['Name'].count().sort_values(ascending=False).head(50))
print(f"\nAvg bill by doctor ",round(dataset.groupby('Doctor')['Billing Amount'].mean(),2).sort_values(ascending=False))
stayVsBilling_result=dataset.groupby(['Stay'])['Billing Amount'].agg( 
    Mean_Billing='mean',
    Min_Billing='min',
    Max_Billing='max',
    Patient_Count='count').round(2)
billing_bins=[0,10000,20000,30000,40000,50000]
billing_label=['0-10k','10k-20k','20k-30k','30k-40k','40k-50k']
dataset['Billing Range']=pd.cut(dataset['Billing Amount'],bins=billing_bins,labels=billing_label)
result=dataset.groupby(['Stay','Billing Range'],observed=True)['Hospital'].count().unstack()
print(result)

Total Doctors:  40341

Top doctor by patients  Doctor
Michael Smith    24
Name: Name, dtype: int64

Avg stay:  16

Avg Bill:  25555.69

Top 10 doctors by patient count:  Doctor
Michael Smith        24
John Smith           21
Robert Smith         19
Michael Johnson      19
David Smith          18
Robert Johnson       17
James Smith          17
Michael Williams     17
Christopher Smith    16
Matthew Smith        16
Name: Name, dtype: int64

Test Results by Doctors:
  Test Results       Abnormal  Inconclusive  Normal  Total
Doctor
Michael Smith          10.0           9.0     5.0   24.0
John Smith              7.0           5.0     9.0   21.0
Robert Smith            5.0           7.0     7.0   19.0
Michael Johnson         5.0           2.0    12.0   19.0
David Smith             5.0           7.0     6.0   18.0
Robert Johnson          6.0           6.0     5.0   17.0
James Smith             6.0           7.0     4.0   17.0
Michael Williams        4.0           5.0     8.0   17.0
Christopher Smith       7.0           6.0     3.0   16.0
Matthew Smith           3.0           3.0    10.0   16.0

Number of patients by hospital:  Hospital
LLC Smith         40
Smith Ltd         35
Johnson PLC       35
Ltd Smith         35
Smith PLC         33
Smith Group       32
Group Smith       30
Johnson Inc       29
Smith Inc         29
Smith LLC         28
LLC Johnson       28
PLC Williams      27
Brown Inc         26
PLC Smith         26
Inc Brown         25
Williams LLC      25
Inc Smith         25
Group Johnson     24
Inc Johnson       24
Johnson Group     24
Brown LLC         24
Inc Jones         23
Group Brown       22
Johnson LLC       20
Johnson Ltd       20
Inc Williams      20
LLC Williams      20
Williams Group    20
Jones Group       20
Brown PLC         20
Brown Group       19
Miller Inc        19
LLC Garcia        19
Jones LLC         19
Ltd Brown         19
Jones Ltd         19
Williams Inc      19
LLC Brown         18
Group Jones       18
Williams Ltd      18
Ltd Johnson       18
Williams PLC      17
Group Davis       17
Miller PLC        17
Brown Ltd         17
LLC Jones         17
Miller Ltd        17
Ltd Jones         17
PLC Brown         16
Miller LLC        16
Name: Name, dtype: int64

Avg bill by doctor  Doctor
Kathleen Griffin       52764.28
Dr. Joseph Gordon      52373.03
Taylor Novak           52271.66
Robert Hartman         52181.84
Brian Riley            52170.04
                         ...
Amy Burnett            -1306.66
Mr. Dean Guzman DDS    -1310.27
Stacey Davenport       -1428.84
Mark Hines             -1520.42
Todd Becker            -2008.49
Name: Billing Amount, Length: 40341, dtype: float64
Billing Range  0-10k  10k-20k  20k-30k  30k-40k  40k-50k
Stay
1                295      360      338      322      309
2                324      334      334      314      327
3                287      304      355      375      309
4                296      346      312      354      335
5                294      341      353      339      323
6                309      352      328      349      369
7                305      329      361      345      340
8                266      352      319      340      356
9                291      350      333      355      335
10               325      303      330      332      337
11               311      355      372      340      322
12               275      352      351      336      317
13               326      350      325      334      323
14               287      332      375      355      348
15               285      351      323      337      320
16               287      331      323      311      335
17               316      319      315      343      315
18               345      323      322      320      324
19               323      349      339      348      317
20               280      381      334      363      348
21               299      384      367      348      344
22               295      315      378      307      303
23               305      323      313      361      350
24               286      311      339      329      306
25               303      342      361      332      316
26               303      304      355      326      331
27               337      324      346      345      333
28               304      308      355      332      349
29               327      343      349      313      322
30               332      323      324      339      341